uint8 ARRAY_SIZE = 3
uint64 timestamp		# time since system start (microseconds)
int32 iter			# Iterative value (debug)

char[25] name			# Message name
float32[3] local_position	# Vehicle Position Array
float32 glob_pose_lat           # Vehicle Global Latitude (degree)
float32 glob_pose_lon           # Vehicle Global longitude (degree)
float32 glob_pose_alt           # Vehicle Altitude ASML (meters)

